const MIN_INDEX_AVATAR = 1;
const MAX_INDEX_AVATAR = 6;

const MIN_INDEX_LIKE = 15;
const MAX_INDEX_LIKE = 200;

const MIN_INDEX_COMMENT = 0;
const MAX_INDEX_COMMENT = 30;

const COUNT_OBJECTS = 25;

export {
  MIN_INDEX_AVATAR,
  MAX_INDEX_AVATAR,
  MIN_INDEX_LIKE,
  MAX_INDEX_LIKE,
  MIN_INDEX_COMMENT,
  MAX_INDEX_COMMENT,
  COUNT_OBJECTS
};
